/**
 * Placeholder data for when the database is unavailable.
 *
 * This allows the site to render fully on Vercel (or local dev)
 * without a running PostgreSQL instance.
 */

// ---------------------------------------------------------------------------
// Vehicle placeholders
// ---------------------------------------------------------------------------

export interface PlaceholderVehicle {
  vin: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  price: number;
  msrp: number;
  mileage: number;
  fuel: string;
  transmission: string;
  gradient: string;
  condition: string;
  bodyStyle: string;
  exteriorColor: string;
  interiorColor: string;
  drivetrain: string;
  engine: string;
  mpg: string;
  stockNumber: string;
  features: string[];
  tag?: string;
  photo: string;
  thumbnail: string;
}

export const placeholderVehicles: PlaceholderVehicle[] = [
  {
    vin: "1HGCV1F34PA000001",
    year: 2024,
    make: "Honda",
    model: "CR-V",
    trim: "EX-L",
    price: 34_250,
    msrp: 36_500,
    mileage: 1_283,
    fuel: "Gasoline",
    transmission: "CVT",
    gradient: "from-blue-400 to-blue-600",
    condition: "New",
    bodyStyle: "SUV",
    exteriorColor: "Radiant Red Metallic",
    interiorColor: "Black Leather",
    drivetrain: "All-Wheel Drive",
    engine: "1.5L Turbocharged 4-Cylinder",
    mpg: "29 city / 36 hwy",
    stockNumber: "WP24-0847",
    photo: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=400&h=300&fit=crop&auto=format",
    tag: "New Arrival",
    features: [
      "Honda Sensing Suite",
      "Leather-Trimmed Seats",
      "Wireless Apple CarPlay & Android Auto",
      "Heated Front & Rear Seats",
      "Power Tailgate with Hands-Free Access",
      "Panoramic Moonroof",
      "9-inch Color Touchscreen",
      "Blind Spot Information System",
      "Remote Engine Start",
      "Dual-Zone Automatic Climate Control",
      "LED Headlights with Auto On/Off",
      "18-inch Alloy Wheels",
    ],
  },
  {
    vin: "5YJ3E1EA1PF000002",
    year: 2023,
    make: "Tesla",
    model: "Model 3",
    trim: "Long Range",
    price: 38_990,
    msrp: 42_990,
    mileage: 12_450,
    fuel: "Electric",
    transmission: "Single-Speed",
    gradient: "from-red-400 to-red-600",
    condition: "Used",
    bodyStyle: "Sedan",
    exteriorColor: "Midnight Silver Metallic",
    interiorColor: "Black Premium",
    drivetrain: "All-Wheel Drive",
    engine: "Dual Motor Electric",
    mpg: "134 MPGe combined",
    stockNumber: "WP23-1102",
    photo: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400&h=300&fit=crop&auto=format",
    tag: "Electric",
    features: [
      "Autopilot",
      "15-inch Touchscreen",
      "Premium Audio System",
      "Glass Roof",
      "Heated Seats All Rows",
      "Wireless Phone Charging",
      "Sentry Mode",
      "Over-the-Air Updates",
      "360 MPG Equivalent",
      "Fast Charging Capable",
      "LED Fog Lights",
      "Power Folding Mirrors",
    ],
  },
  {
    vin: "2T3P1RFV4RC000003",
    year: 2024,
    make: "Toyota",
    model: "RAV4",
    trim: "XLE Premium",
    price: 35_875,
    msrp: 37_200,
    mileage: 856,
    fuel: "Hybrid",
    transmission: "CVT",
    gradient: "from-emerald-400 to-emerald-600",
    condition: "New",
    bodyStyle: "SUV",
    exteriorColor: "Blueprint",
    interiorColor: "Black SofTex",
    drivetrain: "All-Wheel Drive",
    engine: "2.5L 4-Cylinder Hybrid",
    mpg: "41 city / 38 hwy",
    stockNumber: "WP24-0903",
    photo: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=400&h=300&fit=crop&auto=format",
    tag: "New Arrival",
    features: [
      "Toyota Safety Sense 2.5+",
      "8-inch Touchscreen",
      "SofTex Trimmed Seats",
      "Sunroof",
      "Blind Spot Monitor",
      "Rear Cross-Traffic Alert",
      "Wireless Apple CarPlay",
      "Dual-Zone Climate Control",
      "Power Liftgate",
      "LED Headlights",
      "17-inch Alloy Wheels",
      "Adaptive Cruise Control",
    ],
  },
  {
    vin: "5UXTS3C50P9000004",
    year: 2023,
    make: "BMW",
    model: "X3",
    trim: "xDrive30i",
    price: 42_500,
    msrp: 48_750,
    mileage: 8_720,
    fuel: "Gasoline",
    transmission: "8-Speed Auto",
    gradient: "from-slate-500 to-slate-700",
    condition: "Certified",
    bodyStyle: "SUV",
    exteriorColor: "Alpine White",
    interiorColor: "Cognac Vernasca Leather",
    drivetrain: "All-Wheel Drive",
    engine: "2.0L TwinPower Turbo 4-Cylinder",
    mpg: "25 city / 29 hwy",
    stockNumber: "WP23-0781",
    photo: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400&h=300&fit=crop&auto=format",
    tag: "Luxury",
    features: [
      "BMW Live Cockpit Professional",
      "Vernasca Leather Upholstery",
      "Panoramic Moonroof",
      "Parking Assistant Plus",
      "Heated Front Seats",
      "Harman Kardon Sound System",
      "Wireless Charging",
      "Active Driving Assistant",
      "LED Headlights",
      "19-inch Alloy Wheels",
      "Power Tailgate",
      "Head-Up Display",
    ],
  },
  {
    vin: "1G1YA2D4XP5000005",
    year: 2024,
    make: "Chevrolet",
    model: "Corvette",
    trim: "Stingray 2LT",
    price: 68_900,
    msrp: 72_400,
    mileage: 3_210,
    fuel: "Gasoline",
    transmission: "8-Speed DCT",
    gradient: "from-yellow-400 to-orange-500",
    condition: "Used",
    bodyStyle: "Coupe",
    exteriorColor: "Torch Red",
    interiorColor: "Jet Black Mulan Leather",
    drivetrain: "Rear-Wheel Drive",
    engine: "6.2L V8",
    mpg: "16 city / 24 hwy",
    stockNumber: "WP24-0215",
    photo: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=400&h=300&fit=crop&auto=format",
    features: [
      "Performance Exhaust",
      "Magnetic Ride Control",
      "Head-Up Display",
      "Bose 14-Speaker Audio",
      "GT2 Bucket Seats",
      "Performance Data Recorder",
      "Wireless Apple CarPlay",
      "Heated & Ventilated Seats",
      "Front Lift System",
      "Rear Camera Mirror",
      "Carbon Flash Badges",
      "8-inch Touchscreen",
    ],
  },
  {
    vin: "1FTFW1E89PKA00006",
    year: 2023,
    make: "Ford",
    model: "F-150",
    trim: "Lariat",
    price: 52_350,
    msrp: 58_100,
    mileage: 15_680,
    fuel: "Gasoline",
    transmission: "10-Speed Auto",
    gradient: "from-sky-400 to-indigo-500",
    condition: "Used",
    bodyStyle: "Truck",
    exteriorColor: "Iconic Silver Metallic",
    interiorColor: "Black Leather",
    drivetrain: "4x4",
    engine: "3.5L EcoBoost V6",
    mpg: "18 city / 24 hwy",
    stockNumber: "WP23-1450",
    photo: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=400&h=300&fit=crop&auto=format",
    features: [
      "Ford Co-Pilot360 2.0",
      "SYNC 4 with 12-inch Screen",
      "B&O Sound System",
      "Leather-Trimmed Seats",
      "Pro Power Onboard",
      "Tailgate Step",
      "Trailer Tow Package",
      "360-Degree Camera",
      "Heated & Cooled Seats",
      "LED Box Lighting",
      "Spray-In Bedliner",
      "20-inch Chrome Wheels",
    ],
  },
  {
    vin: "5NMJFDAE4PH000007",
    year: 2023,
    make: "Hyundai",
    model: "Tucson",
    trim: "SEL",
    price: 29_800,
    msrp: 32_450,
    mileage: 10_240,
    fuel: "Hybrid",
    transmission: "6-Speed Auto",
    gradient: "from-violet-400 to-violet-600",
    condition: "Used",
    bodyStyle: "SUV",
    exteriorColor: "Deep Sea Blue",
    interiorColor: "Gray Cloth",
    drivetrain: "All-Wheel Drive",
    engine: "1.6L Turbocharged Hybrid",
    mpg: "38 city / 38 hwy",
    stockNumber: "WP23-0655",
    photo: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=400&h=300&fit=crop&auto=format",
    features: [
      "Hyundai SmartSense",
      "8-inch Touchscreen",
      "Wireless Apple CarPlay",
      "Heated Front Seats",
      "Blind Spot Collision Avoidance",
      "LED Headlights",
      "Dual-Zone Climate Control",
      "17-inch Alloy Wheels",
      "Remote Start",
      "Adaptive Cruise Control",
      "Rear Cross-Traffic Alert",
      "Lane Keeping Assist",
    ],
  },
  {
    vin: "JM3KFBDM4R1000008",
    year: 2024,
    make: "Mazda",
    model: "CX-5",
    trim: "Carbon Edition Turbo",
    price: 36_950,
    msrp: 39_150,
    mileage: 2_150,
    fuel: "Gasoline",
    transmission: "6-Speed Auto",
    gradient: "from-amber-400 to-amber-600",
    condition: "New",
    bodyStyle: "SUV",
    exteriorColor: "Polymetal Gray Metallic",
    interiorColor: "Black Leather",
    drivetrain: "All-Wheel Drive",
    engine: "2.5L Turbocharged 4-Cylinder",
    mpg: "22 city / 27 hwy",
    stockNumber: "WP24-0312",
    photo: "https://images.unsplash.com/photo-1606611013016-969c19ba27a5?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1606611013016-969c19ba27a5?w=400&h=300&fit=crop&auto=format",
    tag: "New Arrival",
    features: [
      "Mazda i-Activsense Safety",
      "10.25-inch Infotainment Display",
      "Bose 10-Speaker Audio",
      "Heated Steering Wheel",
      "Heated Front Seats",
      "Power Moonroof",
      "18-inch Gloss Black Wheels",
      "Adaptive Cruise Control",
      "Rear Cross-Traffic Alert",
      "Traffic Jam Assist",
      "Head-Up Display",
      "Wireless Charging",
    ],
  },
  {
    vin: "WBAPH5C55BA000009",
    year: 2023,
    make: "Subaru",
    model: "Outback",
    trim: "Limited",
    price: 33_495,
    msrp: 36_745,
    mileage: 14_320,
    fuel: "Gasoline",
    transmission: "CVT",
    gradient: "from-green-500 to-teal-600",
    condition: "Certified",
    bodyStyle: "Wagon",
    exteriorColor: "Autumn Green Metallic",
    interiorColor: "Warm Ivory Leather",
    drivetrain: "All-Wheel Drive",
    engine: "2.5L Boxer 4-Cylinder",
    mpg: "26 city / 32 hwy",
    stockNumber: "WP23-1288",
    photo: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=400&h=300&fit=crop&auto=format",
    tag: "Certified",
    features: [
      "EyeSight Driver Assist",
      "11.6-inch Touchscreen",
      "Harman Kardon Audio",
      "Leather-Trimmed Seats",
      "Power Rear Gate",
      "Heated Front & Rear Seats",
      "X-Mode with Dual Function",
      "LED Steering Responsive Headlights",
      "18-inch Alloy Wheels",
      "Roof Rails",
      "Wireless Apple CarPlay",
      "Reverse Automatic Braking",
    ],
  },
  {
    vin: "1N4BL4DV5PN000010",
    year: 2024,
    make: "Nissan",
    model: "Altima",
    trim: "SR",
    price: 28_750,
    msrp: 30_500,
    mileage: 4_890,
    fuel: "Gasoline",
    transmission: "CVT",
    gradient: "from-rose-400 to-pink-600",
    condition: "New",
    bodyStyle: "Sedan",
    exteriorColor: "Scarlet Ember Tintcoat",
    interiorColor: "Charcoal Sport Cloth",
    drivetrain: "Front-Wheel Drive",
    engine: "2.5L 4-Cylinder",
    mpg: "28 city / 39 hwy",
    stockNumber: "WP24-0198",
    photo: "https://images.unsplash.com/photo-1621993202323-f438eec934ff?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1621993202323-f438eec934ff?w=400&h=300&fit=crop&auto=format",
    features: [
      "Nissan Safety Shield 360",
      "8-inch Touchscreen",
      "Apple CarPlay & Android Auto",
      "ProPilot Assist",
      "19-inch Wheels",
      "Sport-Tuned Suspension",
      "Zero Gravity Seats",
      "Remote Engine Start",
      "Intelligent Around View Monitor",
      "Rear Automatic Braking",
      "LED Headlights",
      "Dual-Zone Climate Control",
    ],
  },
  {
    vin: "3MW5R7J0XP8000011",
    year: 2023,
    make: "Jeep",
    model: "Grand Cherokee",
    trim: "Limited",
    price: 46_500,
    msrp: 51_200,
    mileage: 19_870,
    fuel: "Gasoline",
    transmission: "8-Speed Auto",
    gradient: "from-stone-500 to-stone-700",
    condition: "Used",
    bodyStyle: "SUV",
    exteriorColor: "Diamond Black Crystal",
    interiorColor: "Global Black Leather",
    drivetrain: "4x4",
    engine: "3.6L Pentastar V6",
    mpg: "19 city / 26 hwy",
    stockNumber: "WP23-0934",
    photo: "https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1533106418989-88406c7cc8ca?w=400&h=300&fit=crop&auto=format",
    features: [
      "Uconnect 5 with 10.1-inch Screen",
      "Nappa Leather Seats",
      "Quadra-Trac II 4x4",
      "Panoramic Sunroof",
      "Harman Kardon 19-Speaker Audio",
      "Active Driving Assist",
      "360-Degree Surround View Camera",
      "Air Suspension",
      "Power Liftgate",
      "Heated & Ventilated Seats",
      "Wireless Charging",
      "20-inch Polished Wheels",
    ],
  },
  {
    vin: "5YJ3E1EA8RF000012",
    year: 2024,
    make: "Tesla",
    model: "Model Y",
    trim: "Long Range",
    price: 44_990,
    msrp: 47_990,
    mileage: 890,
    fuel: "Electric",
    transmission: "Single-Speed",
    gradient: "from-cyan-400 to-blue-500",
    condition: "New",
    bodyStyle: "SUV",
    exteriorColor: "Ultra White",
    interiorColor: "Black Premium",
    drivetrain: "All-Wheel Drive",
    engine: "Dual Motor Electric",
    mpg: "123 MPGe combined",
    stockNumber: "WP24-0567",
    photo: "https://images.unsplash.com/photo-1619317332245-d9a86a79d62b?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1619317332245-d9a86a79d62b?w=400&h=300&fit=crop&auto=format",
    tag: "Electric",
    features: [
      "Autopilot",
      "15-inch Touchscreen",
      "Premium Audio System",
      "Glass Roof",
      "Heated Seats All Rows",
      "Wireless Phone Charging",
      "Sentry Mode",
      "Over-the-Air Updates",
      "Fast Charging Capable",
      "Power Liftgate",
      "Tow Hitch Receiver",
      "Camp Mode",
    ],
  },
  {
    vin: "1GCUYEED5PZ000013",
    year: 2024,
    make: "Chevrolet",
    model: "Silverado 1500",
    trim: "LT Trail Boss",
    price: 54_900,
    msrp: 59_800,
    mileage: 5_430,
    fuel: "Gasoline",
    transmission: "10-Speed Auto",
    gradient: "from-red-600 to-red-800",
    condition: "New",
    bodyStyle: "Truck",
    exteriorColor: "Cherry Red Tintcoat",
    interiorColor: "Jet Black Cloth",
    drivetrain: "4x4",
    engine: "5.3L V8",
    mpg: "16 city / 22 hwy",
    stockNumber: "WP24-0421",
    photo: "https://images.unsplash.com/photo-1583267746897-2cf415887172?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1583267746897-2cf415887172?w=400&h=300&fit=crop&auto=format",
    tag: "New Arrival",
    features: [
      "Chevy Safety Assist",
      "13.4-inch Touchscreen",
      "Off-Road Suspension",
      "2-Speed Transfer Case",
      "Skid Plates",
      "Hill Descent Control",
      "Z71 Off-Road Package",
      "Trailering Package",
      "Spray-On Bedliner",
      "18-inch Goodyear Wrangler Tires",
      "Heated Seats",
      "Remote Start",
    ],
  },
  {
    vin: "WAUENAF48PN000014",
    year: 2023,
    make: "Audi",
    model: "A4",
    trim: "Premium Plus S Line",
    price: 39_750,
    msrp: 45_900,
    mileage: 11_200,
    fuel: "Gasoline",
    transmission: "7-Speed S tronic",
    gradient: "from-gray-600 to-gray-800",
    condition: "Certified",
    bodyStyle: "Sedan",
    exteriorColor: "Mythos Black Metallic",
    interiorColor: "Rotor Gray Leather",
    drivetrain: "All-Wheel Drive",
    engine: "2.0L TFSI 4-Cylinder",
    mpg: "26 city / 34 hwy",
    stockNumber: "WP23-0876",
    photo: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=400&h=300&fit=crop&auto=format",
    tag: "Luxury",
    features: [
      "Audi Pre Sense",
      "Virtual Cockpit Plus",
      "MMI Navigation Plus",
      "Bang & Olufsen 3D Audio",
      "S Line Sport Package",
      "Heated Front Seats",
      "19-inch S Line Wheels",
      "Audi Adaptive Cruise Assist",
      "Parking System Plus",
      "LED Headlights with DRL",
      "Wireless Apple CarPlay",
      "Power Sunroof",
    ],
  },
  {
    vin: "KNDJN2A24P7000015",
    year: 2024,
    make: "Kia",
    model: "Sportage",
    trim: "X-Pro Prestige",
    price: 37_290,
    msrp: 39_490,
    mileage: 1_870,
    fuel: "Hybrid",
    transmission: "6-Speed Auto",
    gradient: "from-orange-400 to-orange-600",
    condition: "New",
    bodyStyle: "SUV",
    exteriorColor: "Dawning Red",
    interiorColor: "Black Leather",
    drivetrain: "All-Wheel Drive",
    engine: "1.6L Turbocharged Hybrid",
    mpg: "38 city / 38 hwy",
    stockNumber: "WP24-0733",
    photo: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=400&h=300&fit=crop&auto=format",
    tag: "Hybrid",
    features: [
      "Kia Drive Wise Safety",
      "12.3-inch Dual Panoramic Display",
      "Harman Kardon Premium Audio",
      "Nappa Leather Seats",
      "Heated & Ventilated Front Seats",
      "Heated Steering Wheel",
      "Panoramic Sunroof",
      "Surround View Monitor",
      "Remote Smart Parking",
      "Highway Driving Assist 2",
      "Wireless Charging",
      "Power Liftgate",
    ],
  },
  {
    vin: "JTDKN3DU5P5000016",
    year: 2024,
    make: "Toyota",
    model: "Camry",
    trim: "XSE",
    price: 32_990,
    msrp: 34_600,
    mileage: 3_210,
    fuel: "Hybrid",
    transmission: "CVT",
    gradient: "from-indigo-400 to-indigo-600",
    condition: "New",
    bodyStyle: "Sedan",
    exteriorColor: "Wind Chill Pearl",
    interiorColor: "Black/Red Sport",
    drivetrain: "Front-Wheel Drive",
    engine: "2.5L 4-Cylinder Hybrid",
    mpg: "44 city / 47 hwy",
    stockNumber: "WP24-0891",
    photo: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400&h=300&fit=crop&auto=format",
    tag: "Hybrid",
    features: [
      "Toyota Safety Sense 3.0",
      "9-inch Touchscreen",
      "JBL Premium Audio",
      "Wireless Apple CarPlay",
      "Heated Sport Seats",
      "Panoramic Glass Roof",
      "LED Headlights",
      "19-inch Black Alloy Wheels",
      "Dual-Zone Climate Control",
      "Blind Spot Monitor",
      "Rear Cross-Traffic Alert",
      "Digital Rearview Mirror",
    ],
  },
  {
    vin: "1V2BPEE45PC000017",
    year: 2023,
    make: "Volkswagen",
    model: "ID.4",
    trim: "Pro S Plus",
    price: 41_500,
    msrp: 48_995,
    mileage: 7_640,
    fuel: "Electric",
    transmission: "Single-Speed",
    gradient: "from-teal-400 to-teal-600",
    condition: "Used",
    bodyStyle: "SUV",
    exteriorColor: "Dusk Blue Metallic",
    interiorColor: "Galaxy Black",
    drivetrain: "All-Wheel Drive",
    engine: "Dual Motor Electric",
    mpg: "97 MPGe combined",
    stockNumber: "WP23-1567",
    photo: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=400&h=300&fit=crop&auto=format",
    tag: "Electric",
    features: [
      "IQ.DRIVE Advanced Safety",
      "12-inch Touchscreen",
      "Harman Kardon Audio",
      "Heated Front & Rear Seats",
      "Panoramic Fixed Glass Roof",
      "Wireless Apple CarPlay",
      "Park Assist Plus",
      "Travel Assist",
      "LED Matrix Headlights",
      "Vehicle-to-Load Capability",
      "DC Fast Charging",
      "Augmented Reality Head-Up Display",
    ],
  },
  {
    vin: "2HKRW2H93PH000018",
    year: 2024,
    make: "Honda",
    model: "Pilot",
    trim: "TrailSport",
    price: 45_800,
    msrp: 48_500,
    mileage: 1_100,
    fuel: "Gasoline",
    transmission: "10-Speed Auto",
    gradient: "from-lime-500 to-green-600",
    condition: "New",
    bodyStyle: "SUV",
    exteriorColor: "Diffused Sky Blue Pearl",
    interiorColor: "Black/Orange TrailSport",
    drivetrain: "All-Wheel Drive",
    engine: "3.5L V6",
    mpg: "19 city / 25 hwy",
    stockNumber: "WP24-0245",
    photo: "https://images.unsplash.com/photo-1568844293986-8d0400f4745b?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1568844293986-8d0400f4745b?w=400&h=300&fit=crop&auto=format",
    tag: "New Arrival",
    features: [
      "Honda Sensing Suite",
      "9-inch Touchscreen",
      "Bose Premium Audio",
      "TrailSport Suspension",
      "All-Terrain Tires",
      "Steel Skid Plates",
      "Heated Front Seats",
      "Wireless Apple CarPlay",
      "CabinWatch & CabinTalk",
      "Hands-Free Power Tailgate",
      "18-inch Off-Road Wheels",
      "Hill Descent Control",
    ],
  },
  {
    vin: "5UXCR6C03P9000019",
    year: 2023,
    make: "BMW",
    model: "X5",
    trim: "xDrive40i M Sport",
    price: 62_900,
    msrp: 71_500,
    mileage: 12_450,
    fuel: "Gasoline",
    transmission: "8-Speed Auto",
    gradient: "from-zinc-600 to-zinc-800",
    condition: "Certified",
    bodyStyle: "SUV",
    exteriorColor: "Mineral White Metallic",
    interiorColor: "Cognac Vernasca Leather",
    drivetrain: "All-Wheel Drive",
    engine: "3.0L TwinPower Turbo 6-Cylinder",
    mpg: "21 city / 26 hwy",
    stockNumber: "WP23-0456",
    photo: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400&h=300&fit=crop&auto=format",
    tag: "Luxury",
    features: [
      "BMW Live Cockpit Professional",
      "M Sport Package",
      "Panoramic Sky Lounge Roof",
      "Bowers & Wilkins Diamond Audio",
      "Vernasca Leather Upholstery",
      "Driving Assistant Professional",
      "Parking Assistant Plus",
      "Gesture Control",
      "Wireless Charging",
      "22-inch M Sport Wheels",
      "Air Suspension",
      "Head-Up Display",
    ],
  },
  {
    vin: "4T1G11AK5PU000020",
    year: 2024,
    make: "Toyota",
    model: "Highlander",
    trim: "Hybrid XLE",
    price: 42_350,
    msrp: 44_990,
    mileage: 2_780,
    fuel: "Hybrid",
    transmission: "CVT",
    gradient: "from-emerald-500 to-teal-600",
    condition: "New",
    bodyStyle: "SUV",
    exteriorColor: "Celestial Silver Metallic",
    interiorColor: "Black SofTex",
    drivetrain: "All-Wheel Drive",
    engine: "2.5L 4-Cylinder Hybrid",
    mpg: "36 city / 35 hwy",
    stockNumber: "WP24-0678",
    photo: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=400&h=300&fit=crop&auto=format",
    tag: "Hybrid",
    features: [
      "Toyota Safety Sense 3.0",
      "12.3-inch Touchscreen",
      "3rd Row Seating",
      "SofTex-Trimmed Seats",
      "Heated Front Seats",
      "Power Liftgate",
      "Dual-Zone Climate Control",
      "Wireless Apple CarPlay",
      "Adaptive Cruise Control",
      "Blind Spot Monitor",
      "18-inch Alloy Wheels",
      "Digital Rearview Mirror",
    ],
  },
  {
    vin: "1G1FE1R78P0000021",
    year: 2023,
    make: "Chevrolet",
    model: "Bolt EUV",
    trim: "Premier",
    price: 27_500,
    msrp: 33_100,
    mileage: 9_870,
    fuel: "Electric",
    transmission: "Single-Speed",
    gradient: "from-blue-500 to-cyan-500",
    condition: "Used",
    bodyStyle: "SUV",
    exteriorColor: "Ice Blue Metallic",
    interiorColor: "Dark Ash Gray",
    drivetrain: "Front-Wheel Drive",
    engine: "Single Motor Electric",
    mpg: "131 MPGe combined",
    stockNumber: "WP23-1789",
    photo: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=400&h=300&fit=crop&auto=format",
    tag: "Electric",
    features: [
      "Chevy Safety Assist",
      "10.2-inch Touchscreen",
      "Bose Premium Audio",
      "Super Cruise Hands-Free Driving",
      "Heated Front Seats",
      "Heated Steering Wheel",
      "Sunroof",
      "Wireless Apple CarPlay",
      "DC Fast Charging",
      "Rear Camera Mirror",
      "Surround Vision",
      "17-inch Alloy Wheels",
    ],
  },
  {
    vin: "1FTEW1EP5PKA00022",
    year: 2024,
    make: "Ford",
    model: "F-150 Lightning",
    trim: "XLT Extended Range",
    price: 57_990,
    msrp: 62_995,
    mileage: 1_540,
    fuel: "Electric",
    transmission: "Single-Speed",
    gradient: "from-blue-600 to-indigo-700",
    condition: "New",
    bodyStyle: "Truck",
    exteriorColor: "Antimatter Blue Metallic",
    interiorColor: "Black Onyx",
    drivetrain: "4x4",
    engine: "Dual Motor Electric",
    mpg: "78 MPGe combined",
    stockNumber: "WP24-0089",
    photo: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&h=600&fit=crop&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=400&h=300&fit=crop&auto=format",
    tag: "Electric",
    features: [
      "Ford Co-Pilot360 2.0",
      "SYNC 4A with 15.5-inch Screen",
      "B&O Sound System",
      "Pro Power Onboard 9.6kW",
      "Intelligent Backup Power",
      "BlueCruise Hands-Free Driving",
      "360-Degree Camera",
      "Tailgate Work Surface",
      "DC Fast Charging",
      "Max Recline Seats",
      "LED Box Lighting",
      "Onboard Scales",
    ],
  },
];

/**
 * Similar vehicles shown on the VDP page.
 */
export const placeholderSimilarVehicles = [
  {
    year: 2024,
    make: "Toyota",
    model: "RAV4 XLE Premium",
    price: 35_875,
    mileage: 856,
    gradient: "from-emerald-400 to-emerald-600",
    vin: "2T3P1RFV4RC000003",
    photo: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop&auto=format",
  },
  {
    year: 2023,
    make: "Hyundai",
    model: "Tucson SEL",
    price: 29_800,
    mileage: 10_240,
    gradient: "from-violet-400 to-violet-600",
    vin: "5NMJFDAE4PH000008",
    photo: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&h=600&fit=crop&auto=format",
  },
  {
    year: 2024,
    make: "Mazda",
    model: "CX-5 Carbon Turbo",
    price: 36_950,
    mileage: 2_150,
    gradient: "from-amber-400 to-amber-600",
    vin: "JM3KFBDM4R1000009",
    photo: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&auto=format",
  },
];

// ---------------------------------------------------------------------------
// Featured vehicles (subset for homepage)
// ---------------------------------------------------------------------------

export const placeholderFeaturedVehicles = placeholderVehicles
  .slice(0, 4)
  .map((v) => ({
    vin: v.vin,
    year: v.year,
    make: v.make,
    model: `${v.model} ${v.trim}`,
    price: v.price,
    mileage: v.mileage,
    gradient: v.gradient,
    tag: v.tag ?? v.condition,
    photo: v.photo,
    bodyStyle: v.bodyStyle,
  }));

// ---------------------------------------------------------------------------
// Lead placeholders
// ---------------------------------------------------------------------------

export interface PlaceholderLead {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  vehicle_interest: string;
  source: string;
  status: string;
  created_at: string;
}

export const placeholderLeads: PlaceholderLead[] = [
  {
    id: "lead-001",
    first_name: "Sarah",
    last_name: "Martinez",
    email: "sarah.m@example.com",
    phone: "+13035551001",
    vehicle_interest: "2024 Honda CR-V EX-L",
    source: "website_form",
    status: "new",
    created_at: "2026-03-25T10:30:00Z",
  },
  {
    id: "lead-002",
    first_name: "James",
    last_name: "Robinson",
    email: "james.r@example.com",
    phone: "+13035551002",
    vehicle_interest: "2023 Tesla Model 3 Long Range",
    source: "vdp_inquiry",
    status: "contacted",
    created_at: "2026-03-24T15:45:00Z",
  },
  {
    id: "lead-003",
    first_name: "Maria",
    last_name: "Lopez",
    email: "maria.l@example.com",
    phone: null,
    vehicle_interest: "Any SUV under $40K",
    source: "chat",
    status: "qualified",
    created_at: "2026-03-24T09:15:00Z",
  },
  {
    id: "lead-004",
    first_name: "David",
    last_name: "Chen",
    email: "david.c@example.com",
    phone: "+13035551004",
    vehicle_interest: "2024 Toyota RAV4 XLE Premium",
    source: "website_form",
    status: "appointment_set",
    created_at: "2026-03-23T14:20:00Z",
  },
  {
    id: "lead-005",
    first_name: "Emily",
    last_name: "Thompson",
    email: "emily.t@example.com",
    phone: "+13035551005",
    vehicle_interest: "2023 BMW X3 xDrive30i",
    source: "third_party",
    status: "sold",
    created_at: "2026-03-22T11:00:00Z",
  },
  {
    id: "lead-006",
    first_name: "Michael",
    last_name: "Brown",
    email: "michael.b@example.com",
    phone: "+13035551006",
    vehicle_interest: "2023 Ford F-150 Lariat",
    source: "phone",
    status: "new",
    created_at: "2026-03-25T08:10:00Z",
  },
  {
    id: "lead-007",
    first_name: "Jessica",
    last_name: "Davis",
    email: "jessica.d@example.com",
    phone: null,
    vehicle_interest: "Electric vehicles",
    source: "website_form",
    status: "contacted",
    created_at: "2026-03-21T16:30:00Z",
  },
  {
    id: "lead-008",
    first_name: "Robert",
    last_name: "Wilson",
    email: "robert.w@example.com",
    phone: "+13035551008",
    vehicle_interest: "2024 Chevrolet Corvette Stingray",
    source: "walk_in",
    status: "lost",
    created_at: "2026-03-20T13:45:00Z",
  },
];

// ---------------------------------------------------------------------------
// Dashboard stats (computed from placeholder data)
// ---------------------------------------------------------------------------

export interface PlaceholderDashboardStats {
  vehicles: {
    total: number;
    available: number;
    pending: number;
    sold: number;
  };
  leads: {
    total: number;
    new: number;
    contacted: number;
    qualified: number;
    appointment_set: number;
    sold: number;
    lost: number;
  };
  avgDaysOnLot: number;
  conversionRate: number;
}

export const placeholderDashboardStats: PlaceholderDashboardStats = {
  vehicles: {
    total: placeholderVehicles.length,
    available: placeholderVehicles.filter((v) => v.condition !== "Used").length,
    pending: 1,
    sold: 0,
  },
  leads: {
    total: placeholderLeads.length,
    new: placeholderLeads.filter((l) => l.status === "new").length,
    contacted: placeholderLeads.filter((l) => l.status === "contacted").length,
    qualified: placeholderLeads.filter((l) => l.status === "qualified").length,
    appointment_set: placeholderLeads.filter((l) => l.status === "appointment_set").length,
    sold: placeholderLeads.filter((l) => l.status === "sold").length,
    lost: placeholderLeads.filter((l) => l.status === "lost").length,
  },
  avgDaysOnLot: 18,
  conversionRate: 14,
};

// ---------------------------------------------------------------------------
// Facets (computed from placeholder vehicles)
// ---------------------------------------------------------------------------

export interface PlaceholderFacets {
  makes: { value: string; count: number }[];
  conditions: { value: string; count: number }[];
  bodyStyles: { value: string; count: number }[];
  years: { value: number; count: number }[];
}

function computeFacets(vehicles: PlaceholderVehicle[]): PlaceholderFacets {
  const makeMap = new Map<string, number>();
  const conditionMap = new Map<string, number>();
  const bodyMap = new Map<string, number>();
  const yearMap = new Map<number, number>();

  for (const v of vehicles) {
    makeMap.set(v.make, (makeMap.get(v.make) ?? 0) + 1);
    conditionMap.set(v.condition, (conditionMap.get(v.condition) ?? 0) + 1);
    bodyMap.set(v.bodyStyle, (bodyMap.get(v.bodyStyle) ?? 0) + 1);
    yearMap.set(v.year, (yearMap.get(v.year) ?? 0) + 1);
  }

  const toArray = <T extends string | number>(map: Map<T, number>) =>
    Array.from(map.entries())
      .map(([value, count]) => ({ value, count }))
      .sort((a, b) => b.count - a.count);

  return {
    makes: toArray(makeMap) as { value: string; count: number }[],
    conditions: toArray(conditionMap) as { value: string; count: number }[],
    bodyStyles: toArray(bodyMap) as { value: string; count: number }[],
    years: (toArray(yearMap) as { value: number; count: number }[]).sort(
      (a, b) => b.value - a.value,
    ),
  };
}

export const placeholderFacets = computeFacets(placeholderVehicles);
