/**
 * Auto-generated by AgenticQA SDETAgent (template fallback)
 * Route: /api/admin/stats
 * Methods: GET
 * Source: api-admin-stats
 */

import { test, expect } from "@playwright/test";

test.describe("GET /api/admin/stats", () => {
  test("returns non-500 status for valid request", async ({ request }) => {
    const resp = await request.get(`/api/admin/stats`);
    expect(resp.status(), "/api/admin/stats must not crash (500)").not.toBe(500);
    expect(resp.status(), "/api/admin/stats must not crash (502)").not.toBe(502);
  });

  test("has required security headers", async ({ request }) => {
    const resp = await request.get(`/api/admin/stats`);
    if (resp.status() !== 404) {
      expect(resp.headers()["x-content-type-options"]).toBe("nosniff");
    }
  });

  test("response has expected shape fields", async ({ request }) => {
    const resp = await request.get(`/api/admin/stats`);
    if (resp.status() !== 200) return; // skip if route not in this build
    const body = await resp.json();
      expect(body).toHaveProperty("avg_days_on_lot");
      expect(body).toHaveProperty("conversion_rate");
      expect(body).toHaveProperty("recent_leads");
  });

});