/**
 * Auto-generated by AgenticQA SDETAgent (template fallback)
 * Route: /api/admin/intake/recommendations
 * Methods: GET
 * Source: api-admin-intake-recommendations
 */

import { test, expect } from "@playwright/test";

test.describe("GET /api/admin/intake/recommendations", () => {
  test("returns non-500 status for valid request", async ({ request }) => {
    const resp = await request.get(`/api/admin/intake/recommendations`);
    expect(resp.status(), "/api/admin/intake/recommendations must not crash (500)").not.toBe(500);
    expect(resp.status(), "/api/admin/intake/recommendations must not crash (502)").not.toBe(502);
  });

  test("has required security headers", async ({ request }) => {
    const resp = await request.get(`/api/admin/intake/recommendations`);
    if (resp.status() !== 404) {
      expect(resp.headers()["x-content-type-options"]).toBe("nosniff");
    }
  });

  test("response has expected shape fields", async ({ request }) => {
    const resp = await request.get(`/api/admin/intake/recommendations`);
    if (resp.status() !== 200) return; // skip if route not in this build
    const body = await resp.json();
      expect(body).toHaveProperty("dealer_id");
      expect(body).toHaveProperty("generated_at");
  });

});