/**
 * Auto-generated by AgenticQA SDETAgent (template fallback)
 * Route: /api/images/[key]
 * Methods: GET
 * Source: api-images-key
 */

import { test, expect } from "@playwright/test";

test.describe("GET /api/images/[key]", () => {
  test("returns non-500 status for valid request", async ({ request }) => {
    const resp = await request.get(`/api/images/[key]`);
    expect(resp.status(), "/api/images/[key] must not crash (500)").not.toBe(500);
    expect(resp.status(), "/api/images/[key] must not crash (502)").not.toBe(502);
  });

  test("returns JSON content-type on success", async ({ request }) => {
    const resp = await request.get(`/api/images/[key]`);
    if (resp.status() === 200) {
      expect(resp.headers()["content-type"]).toContain("application/json");
    }
    expect(resp.status()).not.toBe(500);
  });

  test("has required security headers", async ({ request }) => {
    const resp = await request.get(`/api/images/[key]`);
    if (resp.status() !== 404) {
      expect(resp.headers()["x-content-type-options"]).toBe("nosniff");
    }
  });

});