/**
 * Auto-generated by AgenticQA SDETAgent (template fallback)
 * Route: /api/inventory/spotlight
 * Methods: GET
 * Source: api-inventory-spotlight
 */

import { test, expect } from "@playwright/test";

test.describe("GET /api/inventory/spotlight", () => {
  test("returns non-500 status for valid request", async ({ request }) => {
    const resp = await request.get(`/api/inventory/spotlight?dealer_id=00000000-0000-4000-a000-000000000001`);
    expect(resp.status(), "/api/inventory/spotlight must not crash (500)").not.toBe(500);
    expect(resp.status(), "/api/inventory/spotlight must not crash (502)").not.toBe(502);
  });

  test("returns 400 when required query params are missing", async ({ request }) => {
    // /api/inventory/spotlight requires: dealer_id, limit
    const resp = await request.get(`/api/inventory/spotlight`);
    // 400 = missing params, 404 = route not in this build
    expect([400, 404]).toContain(resp.status());
  });

  test("has required security headers", async ({ request }) => {
    const resp = await request.get(`/api/inventory/spotlight?dealer_id=00000000-0000-4000-a000-000000000001`);
    if (resp.status() !== 404) {
      expect(resp.headers()["x-content-type-options"]).toBe("nosniff");
    }
  });

  test("response has expected shape fields", async ({ request }) => {
    const resp = await request.get(`/api/inventory/spotlight?dealer_id=00000000-0000-4000-a000-000000000001`);
    if (resp.status() !== 200) return; // skip if route not in this build
    const body = await resp.json();
      expect(body).toHaveProperty("total");
      expect(body).toHaveProperty("source");
      expect(body).toHaveProperty("vehicles");
  });

});