/**
 * Auto-generated by AgenticQA SDETAgent (template fallback)
 * Route: /api/admin/leads/[id]
 * Methods: GET, PUT
 * Source: api-admin-leads-id
 */

import { test, expect } from "@playwright/test";

test.describe("GET /api/admin/leads/[id]", () => {
  test("returns non-500 status for valid request", async ({ request }) => {
    const resp = await request.get(`/api/admin/leads/[id]`);
    expect(resp.status(), "/api/admin/leads/[id] must not crash (500)").not.toBe(500);
    expect(resp.status(), "/api/admin/leads/[id] must not crash (502)").not.toBe(502);
  });

  test("has required security headers", async ({ request }) => {
    const resp = await request.get(`/api/admin/leads/[id]`);
    if (resp.status() !== 404) {
      expect(resp.headers()["x-content-type-options"]).toBe("nosniff");
    }
  });

  test("response has expected shape fields", async ({ request }) => {
    const resp = await request.get(`/api/admin/leads/[id]`);
    if (resp.status() !== 200) return; // skip if route not in this build
    const body = await resp.json();
      expect(body).toHaveProperty("lead");
      expect(body).toHaveProperty("field");
      expect(body).toHaveProperty("updated");
      expect(body).toHaveProperty("lead_id");
      expect(body).toHaveProperty("changes");
  });

});

test.describe("PUT /api/admin/leads/[id]", () => {
  test("returns non-500 status for valid request", async ({ request }) => {
    const resp = await request.put(`/api/admin/leads/[id]`, { data: {} });
    expect(resp.status(), "/api/admin/leads/[id] must not crash (500)").not.toBe(500);
    expect(resp.status(), "/api/admin/leads/[id] must not crash (502)").not.toBe(502);
  });

  test("has required security headers", async ({ request }) => {
    const resp = await request.put(`/api/admin/leads/[id]`, { data: {} });
    if (resp.status() !== 404) {
      expect(resp.headers()["x-content-type-options"]).toBe("nosniff");
    }
  });

});