export const dynamic = "force-dynamic";
import type { Metadata } from "next";
import {
  generateInsights,
  hydrateBufferFromDb,
  type BehavioralInsight,
} from "@/lib/analytics-engine";

export const metadata: Metadata = {
  title: "All Insights | Analytics Brain | Admin",
  description: "Complete list of behavioral insights generated by the analytics brain.",
};

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function categoryColor(category: string): string {
  switch (category) {
    case "conversion": return "border-l-emerald-500 bg-emerald-50/50";
    case "engagement": return "border-l-blue-500 bg-blue-50/50";
    case "search": return "border-l-violet-500 bg-violet-50/50";
    case "ux_friction": return "border-l-red-500 bg-red-50/50";
    case "chat": return "border-l-amber-500 bg-amber-50/50";
    case "marketing": return "border-l-pink-500 bg-pink-50/50";
    case "navigation": return "border-l-cyan-500 bg-cyan-50/50";
    default: return "border-l-gray-500 bg-gray-50/50";
  }
}

function confidenceBar(confidence: number): string {
  if (confidence >= 0.8) return "bg-emerald-500";
  if (confidence >= 0.5) return "bg-amber-500";
  return "bg-gray-400";
}

/* ------------------------------------------------------------------ */
/*  Page                                                               */
/* ------------------------------------------------------------------ */

export default async function AllInsightsPage({
  searchParams,
}: {
  searchParams: Promise<{ category?: string }>;
}) {
  await hydrateBufferFromDb();
  const params = await searchParams;

  const allInsights = generateInsights();
  const categoryFilter = params.category;

  // Group and deduplicate
  const grouped = new Map<string, BehavioralInsight[]>();
  for (const insight of allInsights) {
    if (categoryFilter && insight.category !== categoryFilter) continue;
    const list = grouped.get(insight.category) ?? [];
    list.push(insight);
    grouped.set(insight.category, list);
  }

  // Deduplicate within each category
  const dedupedGrouped = new Map<string, BehavioralInsight[]>();
  for (const [cat, insights] of grouped) {
    const seen = new Set<string>();
    const deduped = insights
      .sort((a, b) => b.confidence - a.confidence)
      .filter((insight) => {
        const key = insight.insight.slice(0, 80);
        if (seen.has(key)) return false;
        seen.add(key);
        return true;
      });
    dedupedGrouped.set(cat, deduped);
  }

  const totalDeduped = [...dedupedGrouped.values()].reduce((s, arr) => s + arr.length, 0);
  const categoryOrder = ["conversion", "ux_friction", "engagement", "search", "chat", "marketing", "navigation"];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-3">
            <a
              href="/admin/analytics-brain"
              className="text-sm text-gray-500 hover:text-gray-700 transition-colors"
            >
              &larr; Back to Brain
            </a>
          </div>
          <h1 className="mt-2 text-2xl font-bold text-gray-900">
            {categoryFilter
              ? `${categoryFilter.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())} Insights`
              : "All Insights"}
          </h1>
          <p className="mt-1 text-sm text-gray-500">
            {totalDeduped} unique insights
            {categoryFilter ? ` in ${categoryFilter.replace(/_/g, " ")}` : ` across ${dedupedGrouped.size} categories`}.
            {allInsights.length > totalDeduped && (
              <span className="ml-1 text-gray-400">
                ({allInsights.length - totalDeduped} duplicates hidden)
              </span>
            )}
          </p>
        </div>

        {/* Category filter pills */}
        {!categoryFilter && (
          <div className="hidden sm:flex flex-wrap gap-1.5">
            {categoryOrder.filter((c) => dedupedGrouped.has(c)).map((cat) => (
              <a
                key={cat}
                href={`/admin/analytics-brain/all?category=${cat}`}
                className="rounded-full border border-gray-200 bg-white px-2.5 py-1 text-xs font-medium text-gray-600 transition-colors hover:bg-gray-50"
              >
                {cat.replace(/_/g, " ")} ({dedupedGrouped.get(cat)!.length})
              </a>
            ))}
          </div>
        )}
      </div>

      {/* Category filter (mobile) */}
      {!categoryFilter && (
        <div className="sm:hidden flex flex-wrap gap-1.5">
          {categoryOrder.filter((c) => dedupedGrouped.has(c)).map((cat) => (
            <a
              key={cat}
              href={`/admin/analytics-brain/all?category=${cat}`}
              className="rounded-full border border-gray-200 bg-white px-2.5 py-1 text-xs font-medium text-gray-600 transition-colors hover:bg-gray-50"
            >
              {cat.replace(/_/g, " ")} ({dedupedGrouped.get(cat)!.length})
            </a>
          ))}
        </div>
      )}

      {/* Clear filter */}
      {categoryFilter && (
        <a
          href="/admin/analytics-brain/all"
          className="inline-flex items-center gap-1 rounded-full border border-gray-200 bg-gray-50 px-3 py-1 text-xs font-medium text-gray-600 transition-colors hover:bg-gray-100"
        >
          {categoryFilter.replace(/_/g, " ")} &times;
        </a>
      )}

      {/* Full insight list */}
      <div className="space-y-6">
        {categoryOrder
          .filter((cat) => dedupedGrouped.has(cat))
          .map((cat) => {
            const insights = dedupedGrouped.get(cat)!;
            return (
              <div key={cat}>
                <h3 className="mb-3 text-sm font-semibold uppercase tracking-wider text-gray-500">
                  {cat.replace(/_/g, " ")} ({insights.length})
                </h3>
                <div className="space-y-2">
                  {insights.map((insight) => (
                    <div
                      key={insight.id}
                      className={`rounded-lg border-l-4 p-4 ${categoryColor(insight.category)}`}
                    >
                      <div className="flex items-start justify-between gap-4">
                        <p className="text-sm text-gray-700">{insight.insight}</p>
                        <div className="flex shrink-0 items-center gap-2">
                          <div className="h-1.5 w-12 overflow-hidden rounded-full bg-gray-200">
                            <div
                              className={`h-full rounded-full ${confidenceBar(insight.confidence)}`}
                              style={{ width: `${insight.confidence * 100}%` }}
                            />
                          </div>
                          <span className="text-xs text-gray-400">{(insight.confidence * 100).toFixed(0)}%</span>
                        </div>
                      </div>
                      <p className="mt-1 text-xs text-gray-400">
                        Sample: {insight.sample_size} | Generated: {new Date(insight.generated_at).toLocaleTimeString()}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
      </div>

      {totalDeduped === 0 && (
        <div className="rounded-xl border border-dashed border-gray-300 bg-gray-50 p-12 text-center">
          <h3 className="text-sm font-semibold text-gray-900">No insights found</h3>
          <p className="mt-2 text-sm text-gray-500">
            {categoryFilter
              ? `No insights in the "${categoryFilter.replace(/_/g, " ")}" category yet.`
              : "The brain hasn't generated any insights yet."}
          </p>
          <a
            href="/admin/analytics-brain"
            className="mt-4 inline-block text-sm font-medium text-brand-600 hover:text-brand-700"
          >
            &larr; Back to Brain
          </a>
        </div>
      )}
    </div>
  );
}
