/**
 * AI-powered vehicle listing generator.
 *
 * Strategy 1: OpenAI GPT-4o-mini (if OPENAI_API_KEY is set)
 * Strategy 2: Template-based generation (always available, zero tokens)
 *
 * Generates professional dealer marketing copy, SEO metadata,
 * and key selling-point highlights for each vehicle listing.
 */

import type { Vehicle } from "@/types/vehicle";

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

export interface ListingContent {
  description: string;
  highlights: string[];
  seo_title: string;
  seo_description: string;
  /** Indicates whether the content was generated by AI (true) or templates (false). */
  ai_generated: boolean;
  /** Generation strategy used: "openai" or "template". */
  generation_method: "openai" | "template";
}

/* ------------------------------------------------------------------ */
/*  OpenAI generation (Strategy 1)                                     */
/* ------------------------------------------------------------------ */

async function generateWithOpenAI(vehicle: Partial<Vehicle>): Promise<ListingContent | null> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) return null;

  const vehicleSummary = buildVehicleSummary(vehicle);

  const prompt = `You are an expert automotive copywriter for a dealership website. Write a compelling vehicle listing for the following vehicle. Be professional, accurate, and persuasive.

Vehicle: ${vehicleSummary}

Respond in JSON with these exact fields:
{
  "description": "2-3 paragraph professional description (no markdown)",
  "highlights": ["3-5 key selling points as short bullet strings"],
  "seo_title": "SEO-optimized page title under 60 chars",
  "seo_description": "SEO meta description under 160 chars"
}`;

  try {
    const res = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.7,
        max_tokens: 800,
        response_format: { type: "json_object" },
      }),
      signal: AbortSignal.timeout(15000),
    });

    if (!res.ok) return null;

    const data = (await res.json()) as {
      choices: { message: { content: string } }[];
    };

    const content = data.choices[0]?.message?.content;
    if (!content) return null;

    const parsed = JSON.parse(content) as ListingContent;

    // Validate shape
    if (
      typeof parsed.description !== "string" ||
      !Array.isArray(parsed.highlights) ||
      typeof parsed.seo_title !== "string" ||
      typeof parsed.seo_description !== "string"
    ) {
      return null;
    }

    return { ...parsed, ai_generated: true, generation_method: "openai" as const };
  } catch {
    return null;
  }
}

/* ------------------------------------------------------------------ */
/*  Template generation (Strategy 2 -- always available)               */
/* ------------------------------------------------------------------ */

function generateWithTemplate(vehicle: Partial<Vehicle>): ListingContent {
  const year = vehicle.year ?? new Date().getFullYear();
  const make = vehicle.make ?? "Vehicle";
  const model = vehicle.model ?? "";
  const trim = vehicle.trim ?? "";
  const ymmt = [year, make, model, trim].filter(Boolean).join(" ");

  const condition = vehicle.condition ?? "used";
  const conditionLabel = condition === "new" ? "Brand New" : condition === "certified" ? "Certified Pre-Owned" : "Pre-Owned";

  const mileage = vehicle.mileage ?? 0;
  const mileageStr = mileage > 0 ? `${mileage.toLocaleString()} miles` : "low mileage";

  const price = vehicle.price;
  const priceStr = price ? `$${price.toLocaleString()}` : "";

  const color = vehicle.exterior_color ?? "";
  const drivetrain = formatDrivetrain(vehicle.drivetrain);
  const fuel = formatFuelType(vehicle.fuel_type);
  const transmission = vehicle.transmission ?? "automatic";
  const engine = vehicle.engine ?? "";
  const features = vehicle.features ?? [];
  const bodyStyle = vehicle.body_style ?? "";

  // --- Description ---
  const intro = `This ${conditionLabel.toLowerCase()} ${ymmt}${color ? ` in ${color}` : ""} is ready for its next owner. ${
    bodyStyle ? `As a versatile ${bodyStyle.toLowerCase()}, it` : "It"
  } offers the perfect combination of style, performance, and value${priceStr ? ` at ${priceStr}` : ""}.`;

  const specs = [
    engine ? `Under the hood, you will find a ${engine}` : null,
    `paired with a ${transmission} transmission`,
    drivetrain ? `and ${drivetrain}` : null,
  ]
    .filter(Boolean)
    .join(" ");
  const specsLine = specs ? `${specs}. ` : "";

  const mileageLine =
    condition === "new"
      ? ""
      : `With only ${mileageStr} on the odometer, this ${make} ${model} has plenty of life ahead. `;

  const featuresLine =
    features.length > 0
      ? `Notable features include ${features.slice(0, 5).join(", ")}.`
      : "";

  const closing = `Visit us today to see this ${ymmt} in person and take it for a test drive. Contact our sales team to schedule your appointment or inquire about financing options.`;

  const description = [intro, `${specsLine}${mileageLine}${featuresLine}`, closing]
    .filter((p) => p.trim())
    .join("\n\n");

  // --- Highlights ---
  const highlights = buildHighlights(vehicle);

  // --- SEO ---
  const seo_title = `${ymmt} for Sale${priceStr ? ` | ${priceStr}` : ""}`.substring(0, 60);
  const seo_description = `${conditionLabel} ${ymmt} with ${mileageStr}${priceStr ? ` priced at ${priceStr}` : ""}. ${
    features.length > 0 ? features.slice(0, 3).join(", ") + ". " : ""
  }Schedule a test drive today.`.substring(0, 160);

  return { description, highlights, seo_title, seo_description, ai_generated: false, generation_method: "template" as const };
}

/* ------------------------------------------------------------------ */
/*  Highlight extraction                                               */
/* ------------------------------------------------------------------ */

function buildHighlights(vehicle: Partial<Vehicle>): string[] {
  const highlights: string[] = [];
  const features = vehicle.features ?? [];
  const featuresLower = features.map((f) => f.toLowerCase());

  // Condition / certification
  if (vehicle.condition === "certified") {
    highlights.push("Certified Pre-Owned with manufacturer-backed warranty");
  } else if (vehicle.condition === "new") {
    highlights.push("Brand new with full factory warranty");
  }

  // Low mileage
  if (vehicle.mileage && vehicle.mileage < 30000 && vehicle.condition !== "new") {
    highlights.push(`Low mileage: only ${vehicle.mileage.toLocaleString()} miles`);
  }

  // Drivetrain
  if (vehicle.drivetrain === "awd") {
    highlights.push("All-Wheel Drive for confident handling in all conditions");
  } else if (vehicle.drivetrain === "4wd") {
    highlights.push("4WD capability for on-road and off-road adventures");
  }

  // Fuel efficiency
  if (vehicle.fuel_type === "electric") {
    highlights.push("Fully electric -- zero emissions and low running costs");
  } else if (vehicle.fuel_type === "hybrid" || vehicle.fuel_type === "plug_in_hybrid") {
    highlights.push("Hybrid powertrain for exceptional fuel efficiency");
  } else if (vehicle.mpg_highway && vehicle.mpg_highway >= 30) {
    highlights.push(`Excellent fuel economy: up to ${vehicle.mpg_highway} MPG highway`);
  }

  // Premium features
  const premiumKeywords = [
    { keywords: ["leather", "leather seats"], text: "Premium leather interior" },
    { keywords: ["sunroof", "moonroof", "panoramic"], text: "Panoramic sunroof" },
    { keywords: ["navigation", "nav"], text: "Built-in navigation system" },
    { keywords: ["heated seats", "heated"], text: "Heated seats for comfort" },
    { keywords: ["backup camera", "rearview camera", "360 camera"], text: "Rearview camera for easy parking" },
    { keywords: ["apple carplay", "carplay", "android auto"], text: "Apple CarPlay and Android Auto" },
    { keywords: ["adaptive cruise", "cruise control"], text: "Adaptive cruise control" },
    { keywords: ["blind spot", "blind-spot"], text: "Blind spot monitoring" },
  ];

  for (const pf of premiumKeywords) {
    if (highlights.length >= 5) break;
    if (pf.keywords.some((kw) => featuresLower.some((f) => f.includes(kw)))) {
      highlights.push(pf.text);
    }
  }

  // Ensure at least 3 highlights
  if (highlights.length < 3 && vehicle.engine) {
    highlights.push(`${vehicle.engine} engine`);
  }
  if (highlights.length < 3 && vehicle.transmission) {
    highlights.push(`${vehicle.transmission.charAt(0).toUpperCase() + vehicle.transmission.slice(1)} transmission`);
  }
  if (highlights.length < 3 && vehicle.body_style) {
    highlights.push(`${vehicle.body_style} body style`);
  }

  return highlights.slice(0, 5);
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function buildVehicleSummary(vehicle: Partial<Vehicle>): string {
  const parts = [
    `${vehicle.year ?? ""} ${vehicle.make ?? ""} ${vehicle.model ?? ""} ${vehicle.trim ?? ""}`.trim(),
    vehicle.condition ? `Condition: ${vehicle.condition}` : null,
    vehicle.mileage ? `Mileage: ${vehicle.mileage.toLocaleString()}` : null,
    vehicle.price ? `Price: $${vehicle.price.toLocaleString()}` : null,
    vehicle.exterior_color ? `Exterior: ${vehicle.exterior_color}` : null,
    vehicle.interior_color ? `Interior: ${vehicle.interior_color}` : null,
    vehicle.engine ? `Engine: ${vehicle.engine}` : null,
    vehicle.transmission ? `Transmission: ${vehicle.transmission}` : null,
    vehicle.drivetrain ? `Drivetrain: ${vehicle.drivetrain}` : null,
    vehicle.fuel_type ? `Fuel: ${vehicle.fuel_type}` : null,
    vehicle.body_style ? `Body: ${vehicle.body_style}` : null,
    vehicle.features && vehicle.features.length > 0
      ? `Features: ${vehicle.features.join(", ")}`
      : null,
  ];
  return parts.filter(Boolean).join("\n");
}

function formatDrivetrain(dt: string | undefined): string {
  const map: Record<string, string> = {
    fwd: "front-wheel drive",
    rwd: "rear-wheel drive",
    awd: "all-wheel drive",
    "4wd": "four-wheel drive",
  };
  return dt ? map[dt] ?? dt : "";
}

function formatFuelType(ft: string | undefined): string {
  const map: Record<string, string> = {
    gasoline: "gasoline",
    diesel: "diesel",
    electric: "electric",
    hybrid: "hybrid",
    plug_in_hybrid: "plug-in hybrid",
  };
  return ft ? map[ft] ?? ft : "";
}

/* ------------------------------------------------------------------ */
/*  Public API                                                         */
/* ------------------------------------------------------------------ */

/**
 * Generate professional listing content for a vehicle.
 *
 * Tries OpenAI GPT-4o-mini first (if OPENAI_API_KEY is set),
 * then falls back to template-based generation (zero tokens, zero cost).
 */
export async function generateListing(vehicle: Partial<Vehicle>): Promise<ListingContent> {
  // Strategy 1: OpenAI
  const aiResult = await generateWithOpenAI(vehicle);
  if (aiResult) return aiResult;

  // Strategy 2: Template (always available)
  return generateWithTemplate(vehicle);
}
